### ISSUE TITLE
I have a data problem

### ISSUE THREAD

**Issue by Liudeke** [zalo/TetSim#5]
First of all thank you very much，How is this data generated
![image](https://user-images.githubusercontent.com/30310819/155643010-a361b8d0-7fd1-42cd-9acc-0757ee609519.png)
Thank you very much for your reply

**Comment by zalo** [comment]
This dragon model was derived from @matthias-research's implementation here:
https://matthias-research.github.io/pages/challenges/softBody.html
Perhaps he can relate if the tool used to produce this is open-source?

In #4 I began to add the ability to import .msh files, but haven't fully completed it (it only supports a maximum of 31 connections per vertex and hasn't been tested very much).

**Comment by zalo** [comment]
Matthias just made a video and released source code for a Tetrahedralizer in Blender, which should output the data you are interested in.

https://youtu.be/sNxz_Ht6Y1Y
